steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/<YOUR_PROJECT_ID>/sample_docker_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/<YOUR_PROJECT_ID>/sample_docker_app']
